// Code generated by goctl. DO NOT EDIT.
// Source: product.proto

package server

import (
	"context"

	"epick-mall/service/product/rpc/internal/logic"
	"epick-mall/service/product/rpc/internal/svc"
	"epick-mall/service/product/rpc/product"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServer) ProductAdd(ctx context.Context, in *product.ProductAddReq) (*product.ProductAddResp, error) {
	l := logic.NewProductAddLogic(ctx, s.svcCtx)
	return l.ProductAdd(in)
}
