// Code generated by goctl. DO NOT EDIT.
// Source: sms.proto

package server

import (
	"context"

	"epick-mall/service/sms/rpc/internal/logic"
	"epick-mall/service/sms/rpc/internal/svc"
	"epick-mall/service/sms/rpc/sms"
)

type SmsServer struct {
	svcCtx *svc.ServiceContext
	sms.UnimplementedSmsServer
}

func NewSmsServer(svcCtx *svc.ServiceContext) *SmsServer {
	return &SmsServer{
		svcCtx: svcCtx,
	}
}

func (s *SmsServer) CouponAdd(ctx context.Context, in *sms.CouponAddReq) (*sms.CouponAddResp, error) {
	l := logic.NewCouponAddLogic(ctx, s.svcCtx)
	return l.CouponAdd(in)
}

func (s *SmsServer) CouponUpdate(ctx context.Context, in *sms.CouponUpdateReq) (*sms.CouponUpdateResp, error) {
	l := logic.NewCouponUpdateLogic(ctx, s.svcCtx)
	return l.CouponUpdate(in)
}

func (s *SmsServer) CouponDelete(ctx context.Context, in *sms.CouponDeleteReq) (*sms.CouponDeleteResp, error) {
	l := logic.NewCouponDeleteLogic(ctx, s.svcCtx)
	return l.CouponDelete(in)
}

func (s *SmsServer) CouponList(ctx context.Context, in *sms.CouponListReq) (*sms.CouponListResp, error) {
	l := logic.NewCouponListLogic(ctx, s.svcCtx)
	return l.CouponList(in)
}

func (s *SmsServer) HomeAdvertiseAdd(ctx context.Context, in *sms.HomeAdvertiseAddReq) (*sms.HomeAdvertiseAddResp, error) {
	l := logic.NewHomeAdvertiseAddLogic(ctx, s.svcCtx)
	return l.HomeAdvertiseAdd(in)
}

func (s *SmsServer) HomeAdvertiseList(ctx context.Context, in *sms.HomeAdvertiseListReq) (*sms.HomeAdvertiseListResp, error) {
	l := logic.NewHomeAdvertiseListLogic(ctx, s.svcCtx)
	return l.HomeAdvertiseList(in)
}

func (s *SmsServer) HomeAdvertiseUpdate(ctx context.Context, in *sms.HomeAdvertiseUpdateReq) (*sms.HomeAdvertiseUpdateResp, error) {
	l := logic.NewHomeAdvertiseUpdateLogic(ctx, s.svcCtx)
	return l.HomeAdvertiseUpdate(in)
}

func (s *SmsServer) HomeAdvertiseDelete(ctx context.Context, in *sms.HomeAdvertiseDeleteReq) (*sms.HomeAdvertiseDeleteResp, error) {
	l := logic.NewHomeAdvertiseDeleteLogic(ctx, s.svcCtx)
	return l.HomeAdvertiseDelete(in)
}
