// Code generated by goctl. DO NOT EDIT.
// Source: sms.proto

package smsclient

import (
	"context"

	"epick-mall/service/sms/rpc/sms"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CouponAddReq            = sms.CouponAddReq
	CouponAddResp           = sms.CouponAddResp
	CouponDeleteReq         = sms.CouponDeleteReq
	CouponDeleteResp        = sms.CouponDeleteResp
	CouponListData          = sms.CouponListData
	CouponListReq           = sms.CouponListReq
	CouponListResp          = sms.CouponListResp
	CouponUpdateReq         = sms.CouponUpdateReq
	CouponUpdateResp        = sms.CouponUpdateResp
	HomeAdvertiseAddReq     = sms.HomeAdvertiseAddReq
	HomeAdvertiseAddResp    = sms.HomeAdvertiseAddResp
	HomeAdvertiseDeleteReq  = sms.HomeAdvertiseDeleteReq
	HomeAdvertiseDeleteResp = sms.HomeAdvertiseDeleteResp
	HomeAdvertiseListData   = sms.HomeAdvertiseListData
	HomeAdvertiseListReq    = sms.HomeAdvertiseListReq
	HomeAdvertiseListResp   = sms.HomeAdvertiseListResp
	HomeAdvertiseUpdateReq  = sms.HomeAdvertiseUpdateReq
	HomeAdvertiseUpdateResp = sms.HomeAdvertiseUpdateResp

	Sms interface {
		CouponAdd(ctx context.Context, in *CouponAddReq, opts ...grpc.CallOption) (*CouponAddResp, error)
		CouponUpdate(ctx context.Context, in *CouponUpdateReq, opts ...grpc.CallOption) (*CouponUpdateResp, error)
		CouponDelete(ctx context.Context, in *CouponDeleteReq, opts ...grpc.CallOption) (*CouponDeleteResp, error)
		CouponList(ctx context.Context, in *CouponListReq, opts ...grpc.CallOption) (*CouponListResp, error)
		HomeAdvertiseAdd(ctx context.Context, in *HomeAdvertiseAddReq, opts ...grpc.CallOption) (*HomeAdvertiseAddResp, error)
		HomeAdvertiseList(ctx context.Context, in *HomeAdvertiseListReq, opts ...grpc.CallOption) (*HomeAdvertiseListResp, error)
		HomeAdvertiseUpdate(ctx context.Context, in *HomeAdvertiseUpdateReq, opts ...grpc.CallOption) (*HomeAdvertiseUpdateResp, error)
		HomeAdvertiseDelete(ctx context.Context, in *HomeAdvertiseDeleteReq, opts ...grpc.CallOption) (*HomeAdvertiseDeleteResp, error)
	}

	defaultSms struct {
		cli zrpc.Client
	}
)

func NewSms(cli zrpc.Client) Sms {
	return &defaultSms{
		cli: cli,
	}
}

func (m *defaultSms) CouponAdd(ctx context.Context, in *CouponAddReq, opts ...grpc.CallOption) (*CouponAddResp, error) {
	client := sms.NewSmsClient(m.cli.Conn())
	return client.CouponAdd(ctx, in, opts...)
}

func (m *defaultSms) CouponUpdate(ctx context.Context, in *CouponUpdateReq, opts ...grpc.CallOption) (*CouponUpdateResp, error) {
	client := sms.NewSmsClient(m.cli.Conn())
	return client.CouponUpdate(ctx, in, opts...)
}

func (m *defaultSms) CouponDelete(ctx context.Context, in *CouponDeleteReq, opts ...grpc.CallOption) (*CouponDeleteResp, error) {
	client := sms.NewSmsClient(m.cli.Conn())
	return client.CouponDelete(ctx, in, opts...)
}

func (m *defaultSms) CouponList(ctx context.Context, in *CouponListReq, opts ...grpc.CallOption) (*CouponListResp, error) {
	client := sms.NewSmsClient(m.cli.Conn())
	return client.CouponList(ctx, in, opts...)
}

func (m *defaultSms) HomeAdvertiseAdd(ctx context.Context, in *HomeAdvertiseAddReq, opts ...grpc.CallOption) (*HomeAdvertiseAddResp, error) {
	client := sms.NewSmsClient(m.cli.Conn())
	return client.HomeAdvertiseAdd(ctx, in, opts...)
}

func (m *defaultSms) HomeAdvertiseList(ctx context.Context, in *HomeAdvertiseListReq, opts ...grpc.CallOption) (*HomeAdvertiseListResp, error) {
	client := sms.NewSmsClient(m.cli.Conn())
	return client.HomeAdvertiseList(ctx, in, opts...)
}

func (m *defaultSms) HomeAdvertiseUpdate(ctx context.Context, in *HomeAdvertiseUpdateReq, opts ...grpc.CallOption) (*HomeAdvertiseUpdateResp, error) {
	client := sms.NewSmsClient(m.cli.Conn())
	return client.HomeAdvertiseUpdate(ctx, in, opts...)
}

func (m *defaultSms) HomeAdvertiseDelete(ctx context.Context, in *HomeAdvertiseDeleteReq, opts ...grpc.CallOption) (*HomeAdvertiseDeleteResp, error) {
	client := sms.NewSmsClient(m.cli.Conn())
	return client.HomeAdvertiseDelete(ctx, in, opts...)
}
