// Code generated by goctl. DO NOT EDIT.
// Source: coupon.proto

package server

import (
	"context"

	"epick-mall/service/coupon/rpc/coupon"
	"epick-mall/service/coupon/rpc/internal/logic"
	"epick-mall/service/coupon/rpc/internal/svc"
)

type CouponServer struct {
	svcCtx *svc.ServiceContext
	coupon.UnimplementedCouponServer
}

func NewCouponServer(svcCtx *svc.ServiceContext) *CouponServer {
	return &CouponServer{
		svcCtx: svcCtx,
	}
}

func (s *CouponServer) CouponAdd(ctx context.Context, in *coupon.CouponAddReq) (*coupon.CouponAddResp, error) {
	l := logic.NewCouponAddLogic(ctx, s.svcCtx)
	return l.CouponAdd(in)
}

func (s *CouponServer) CouponList(ctx context.Context, in *coupon.CouponListReq) (*coupon.CouponListResp, error) {
	l := logic.NewCouponListLogic(ctx, s.svcCtx)
	return l.CouponList(in)
}

func (s *CouponServer) CouponUpdate(ctx context.Context, in *coupon.CouponUpdateReq) (*coupon.CouponUpdateResp, error) {
	l := logic.NewCouponUpdateLogic(ctx, s.svcCtx)
	return l.CouponUpdate(in)
}

func (s *CouponServer) CouponDelete(ctx context.Context, in *coupon.CouponDeleteReq) (*coupon.CouponDeleteResp, error) {
	l := logic.NewCouponDeleteLogic(ctx, s.svcCtx)
	return l.CouponDelete(in)
}
